services:
  LEPAFF\SiteMonitor\Command\SitesCommand:
    tags:
      - name: 'console.command'
        command: 'sitemonitor:sites'
        description: 'An example description for a command'
        # not required, defaults to false
        hidden: false
